sudo: required

language: python

python:
  - "3.5"

services:
  - "docker"

install:
  - "pip install -r requirements.txt"
  - "sudo apt install libpq-dev python3-dev"

script: 
  #- "docker build --file /home/travis/build/Highpelapalo/course/Dockerfile -t firstimage ."
  #- "docker run -d -p 80:5000 firstimage"
  - "./docker_build"
  - "./docker_run"
  - "pytest --cov=." 

after_success:
  - "coveralls"
