sudo: required

language: python

python:
  - "3.5"

services:
  - "docker"

install: "pip install -r requirements.txt"

script: 
  - "docker build --file ~/Dockerfile -t firstimage ."
  - "docker run -p 80:5000 firstimage"
  - "pytest --cov=." 

after_success:
  - "coveralls"
